default_language_version:
  python: python3.11

ci:
  autofix_commit_msg: |
    ci: auto fixes from pre-commit.com hooks
    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: "develop"
  autoupdate_commit_msg: "ci: pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip: [poetry-check, poetry-lock, poetry-export]

repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          [
            "add",
            "ci",
            "docs",
            "feat",
            "bug",
            "fix",
            "refactor",
            "revert",
            "test",
            "security",
            "perf",
            "resolve",
            "merge",
            "maintain",
          ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-xml
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: fix-byte-order-marker
      - id: forbid-new-submodules
      - id: forbid-submodules
      - id: detect-private-key

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-use-type-annotations
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: text-unicode-replacement-char

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter

  - repo: https://github.com/bwhmather/ssort
    rev: v0.11.6
    hooks:
      - id: ssort

  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black
        args: ["--line-length=88"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.1.3"
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
        args:
          - "--config-file=pyproject.toml"
        exclude: "tests"

  -   repo: https://github.com/python-poetry/poetry
      rev: '1.6.0'
      hooks:
      -   id: poetry-check
      -   id: poetry-lock
      -   id: poetry-export
