name: CodeCov

on: [pull_request]

jobs:
  code-coverage:
    name: Create code coverage report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install poetry
        run: |
          python -m venv env
          source env/bin/activate
          pip install "passsssword[tests]"
          pytest --cov tests/python --cov-report term-missing --cov-report xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
